[package]
name = "A-Level-RSA"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modinverse = "0.1.1"
num = "0.4.0"
num-primes = "0.3.0"
